services:
  - type: web
    name: tarka-quiz-server
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
